import{a as S,S as q,i as a}from"./assets/vendor-Db2TdIkw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const A="49718330-58801d0a59045377f458b76fd",R="https://pixabay.com/api/",E=15;async function p(s,t=1){const r={key:A,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:E,page:t};return(await S.get(R,{params:r})).data}const h=document.querySelector(".gallery"),g=document.querySelector(".loader"),y=document.querySelector(".load-more"),B=new q(".gallery a");function L(s){const t=s.map(r=>`
  <li class="gallery-item">
    <a href="${r.largeImageURL}">
      <img src="${r.webformatURL}" alt="${r.tags}" />
    </a>
    <div class="info">
      <p><b>Likes:</b> ${r.likes}</p>
      <p><b>Views:</b> ${r.views}</p>
      <p><b>Comments:</b> ${r.comments}</p>
      <p><b>Downloads:</b> ${r.downloads}</p>
    </div>
  </li>
`).join("");h.insertAdjacentHTML("beforeend",t),B.refresh()}function M(){h.innerHTML=""}function b(){g.classList.remove("is-hidden")}function l(){g.classList.add("is-hidden")}function w(){y.classList.remove("is-hidden")}function m(){y.classList.add("is-hidden")}const v=document.querySelector(".form"),f=v.elements["search-text"],$=document.querySelector(".load-more");m();l();let c="",n=1,u=0;v.addEventListener("submit",async s=>{if(s.preventDefault(),c=f.value.trim(),n=1,!c){a.warning({message:"Please enter a search term",position:"topRight"}),l();return}M(),m(),b();try{const t=await p(c,n);if(u=t.totalHits,t.hits.length===0){a.info({message:"No images found. Try another keyword.",position:"topRight"});return}L(t.hits),P(),u>n*15&&w()}catch{a.error({message:"Error fetching images.",position:"topRight"})}finally{l(),f.value=""}});$.addEventListener("click",async()=>{n++,b(),m();try{const s=await p(c,n);L(s.hits),P(),n*15>=u?a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):w()}catch{a.error({message:"Error loading more images.",position:"topRight"})}finally{l()}});function P(){const s=document.querySelectorAll(".gallery-item"),t=Array.from(s).slice(-15),i=t.flatMap(e=>Array.from(e.querySelectorAll("img"))).map(e=>e.complete?Promise.resolve():new Promise(o=>{e.onload=e.onerror=o}));Promise.all(i).then(()=>{const e=t[0];if(e){const{height:o}=e.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}})}
//# sourceMappingURL=index.js.map
