import{a as q,S as R,i as a}from"./assets/vendor-Db2TdIkw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const E="49718330-58801d0a59045377f458b76fd",A="https://pixabay.com/api/",B=15;async function f(s,t=1){const o={key:E,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:B,page:t};return(await q.get(A,{params:o})).data}const m=document.querySelector(".gallery"),p=document.querySelector(".loader"),h=document.querySelector(".load-more"),M=new R(".gallery a");function g(s){const t=s.map(o=>`
  <li class="gallery-item">
    <a href="${o.largeImageURL}">
      <img src="${o.webformatURL}" alt="${o.tags}" />
    </a>
    <div class="info">
      <p><b>Likes:</b> ${o.likes}</p>
      <p><b>Views:</b> ${o.views}</p>
      <p><b>Comments:</b> ${o.comments}</p>
      <p><b>Downloads:</b> ${o.downloads}</p>
    </div>
  </li>
`).join("");m.insertAdjacentHTML("beforeend",t),M.refresh()}function P(){m.innerHTML=""}function y(){p.classList.add("visible")}function b(){p.classList.remove("visible")}function L(){h.classList.add("visible")}function v(){h.classList.remove("visible")}const w=document.querySelector(".form"),u=w.elements["search-text"],$=document.querySelector(".load-more");let c="",i=1,d=0;w.addEventListener("submit",async s=>{if(s.preventDefault(),c=u.value.trim(),i=1,!c){a.warning({message:"Please enter a search term",position:"topRight"});return}P(),v(),y();try{const t=await f(c,i);if(d=t.totalHits,t.hits.length===0){a.info({message:"No images found. Try another keyword.",position:"topRight"});return}g(t.hits),S(),d>i*15&&L()}catch{a.error({message:"Error fetching images.",position:"topRight"})}finally{b(),u.value=""}});$.addEventListener("click",async()=>{i++,y(),v();try{const s=await f(c,i);g(s.hits),S(),i*15>=d?a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):L()}catch{a.error({message:"Error loading more images.",position:"topRight"})}finally{b()}});function S(){new MutationObserver((t,o)=>{const n=document.querySelectorAll(".gallery-item"),e=n[n.length-1];if(e){const{height:r}=e.getBoundingClientRect();requestAnimationFrame(()=>{window.scrollBy({top:r*2,behavior:"smooth"})}),o.disconnect()}}).observe(document.querySelector(".gallery"),{childList:!0})}
//# sourceMappingURL=index.js.map
