import{a as R,S as q,i as n}from"./assets/vendor-Db2TdIkw.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const E="49718330-58801d0a59045377f458b76fd",B="https://pixabay.com/api/",P=15;async function f(r,e=1){const o={key:E,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:P,page:e};return(await R.get(B,{params:o})).data}const m=document.querySelector(".gallery"),p=document.querySelector(".loader"),h=document.querySelector(".load-more"),$=new q(".gallery a");function g(r){const e=r.map(o=>`
  <li class="gallery-item">
    <a href="${o.largeImageURL}">
      <img src="${o.webformatURL}" alt="${o.tags}" />
    </a>
    <div class="info">
      <p><b>Likes:</b> ${o.likes}</p>
      <p><b>Views:</b> ${o.views}</p>
      <p><b>Comments:</b> ${o.comments}</p>
      <p><b>Downloads:</b> ${o.downloads}</p>
    </div>
  </li>
`).join("");m.insertAdjacentHTML("beforeend",e),$.refresh()}function A(){m.innerHTML=""}function y(){p.classList.add("visible")}function b(){p.classList.remove("visible")}function L(){h.classList.add("visible")}function v(){h.classList.remove("visible")}const w=document.querySelector(".form"),u=w.elements["search-text"],I=document.querySelector(".load-more");let a="",i=1,d=0;w.addEventListener("submit",async r=>{if(r.preventDefault(),a=u.value.trim(),i=1,!a){n.warning({message:"Please enter a search term",position:"topRight"});return}A(),v(),y();try{const e=await f(a,i);if(d=e.totalHits,e.hits.length===0){n.info({message:"No images found. Try another keyword.",position:"topRight"});return}g(e.hits),S(),d>i*15&&L()}catch{n.error({message:"Error fetching images.",position:"topRight"})}finally{b(),u.value=""}});I.addEventListener("click",async()=>{i++,y(),v();try{const r=await f(a,i);g(r.hits),S(),i*15>=d?n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):L()}catch{n.error({message:"Error loading more images.",position:"topRight"})}finally{b()}});function S(){setTimeout(()=>{const r=document.querySelectorAll(".gallery-item"),e=r[r.length-1];if(e){const{height:o}=e.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}},200)}
//# sourceMappingURL=index.js.map
